Repository kubernetes-sigs/porche, pull requests merged in 2022-11, with the labels that each got.

#2 Update OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, size/S, lgtm

#3 Update Security contacts
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1 Initial build infrastructure
  .golangci.yml
  cmd/redirectserver/main.go
  dev/boilerplate.txt
  dev/build
  dev/build-go
  dev/build-images
  dev/ci/presubmit-build
  dev/ci/presubmit-lint
  dev/ci/presubmit-test
  dev/ci/presubmit-verify
  dev/format
  dev/format-go
  dev/format-headers
  dev/helpers/ci-install-shellcheck.sh
  dev/helpers/error-if-changes.sh
  dev/lint
  dev/lint-go
  dev/lint-shell
  dev/test
  dev/test-go
  go.mod
Labels: approved, size/XL, cncf-cla: yes, lgtm

#4 Initial code spike for redirection service
  cmd/redirectserver/README.md
  cmd/redirectserver/app/buckets.go
  cmd/redirectserver/app/buckets_test.go
  cmd/redirectserver/app/handlers.go
  cmd/redirectserver/app/handlers_test.go
  cmd/redirectserver/docs/request-handling.md
  cmd/redirectserver/docs/testing.md
  cmd/redirectserver/main.go
  cmd/redirectserver/main_test.go
  cmd/redirectserver/pkg/blobcache/blobchecker.go
  cmd/redirectserver/pkg/mocks3/server.go
  cmd/redirectserver/pkg/mocks3/server_test.go
  go.mod
  go.sum
  internal/integration/doc.go
  internal/integration/paths.go
  internal/integration/paths_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm

#5 Add .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, size/S, lgtm

#7 Don't build multiarch images
  dev/build-images
Labels: approved, cncf-cla: yes, lgtm, size/XS
